
-- local icons = {
--     dap = {
--       Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
--       Breakpoint = " ",
--       BreakpointCondition = " ",
--       BreakpointRejected = { " ", "DiagnosticError" },
--       LogPoint = ".>",
--     },
--     diagnostics = {
--       Error = " ",
--       Warn = " ",
--       Hint = " ",
--       Info = " ",
--     },
--     git = {
--       added = " ",
--       modified = " ",
--       removed = " ",
--     },
--     kinds = {
--       Array = " ",
--       Boolean = " ",
--       Class = " ",
--       Color = " ",
--       Constant = " ",
--       Constructor = " ",
--       Copilot = " ",
--       Enum = " ",
--       EnumMember = " ",
--       Event = " ",
--       Field = " ",
--       File = " ",
--       Folder = " ",
--       Function = " ",
--       Interface = " ",
--       Key = " ",
--       Keyword = " ",
--       Method = " ",
--       Module = " ",
--       Namespace = " ",
--       Null = " ",
--       Number = " ",
--       Object = " ",
--       Operator = " ",
--       Package = " ",
--       Property = " ",
--       Reference = " ",
--       Snippet = " ",
--       String = " ",
--       Struct = " ",
--       Text = " ",
--       TypeParameter = " ",
--       Unit = " ",
--       Value = " ",
--       Variable = " ",
-- 	}
-- }
--

local icons = {
    dap = {
      Stopped = { "s ", "DiagnosticWarn", "DapStoppedLine" },
      Breakpoint = "b ",
      BreakpointCondition = "bc ",
      BreakpointRejected = { "br ", "DiagnosticError" },
      LogPoint = ".>",
    },
    diagnostics = {
      Error = "E ",
      Warn = "W ",
      Hint = "H ",
      Info = "I ",
    },
    git = {
      added = "+ ",
      modified = "~ ",
      removed = "- ",
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = " ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Text = " ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
	}
}
